version: '3'

services:
  api:
    build: rotten-eggs-api/.
    ports:
      - "8000:8000"
    volumes:
      - ./rotten-eggs-api:/code
  web:
    build: rotten-eggs-web/.
    ports:
    - "80:3000"
    stdin_open: true
    volumes:
      - ./rotten-eggs-web/src:/app/src
    depends_on:
      - api
